from src.providers.currency_provider_cbr import CurrencyProviderCBR
from src.providers.vacancy_provider_head_hunter import VacancyProviderHeadHunter
from src.providers.vacancy_provider_superjob import VacancyProviderSuperjob
from src.providers.http_request_provider_base import HttpRequestProviderBase
